### PR TITLE
feat(button component): button component based on chakra button compo…

### PR DESCRIPTION
**Pull request by govindsingh55**
button component based on chakra button component

### CODE REVIEW

**Comment by prasanna1211** [comment]
Looks nice. There are a few changes that we are going to make when compared with chakra.
1. Preloader in the button can be on left / right. Chakra has it only on left.
2. The space between preloader and the text can be varied.
3. FullWidth button, outline button dot notation is missing.  Reason was RFC didn't include our slack discussion. This is the reason to have discussions in here and managing it in RFCs so that we don't miss something in future.

**Comment by prasanna1211** [comment]
Also dot notation for primary secondary is missing

**Comment by prasanna1211** [comment]
Can we have just an icon with button ? Probably something like a circled button with just icon alone ?

**Comment by govindsingh55** [comment]
> Also dot notation for primary secondary is missing

primary and secondary are probably the color variation right
we can not define this color button is primary and this color button is secondary

**Comment by navin-moorthy** [comment]
image

Small doubt, even if chakra exposes those. Our goal is to build components based on our app needs right?
Why we have jumped to build components in general use?

**Comment by prasanna1211** [comment]
@navin-moorthy Ideal goal is to have wrappers on chakra for whatever it is missing (+) have a theme that is going to make it look good (with animations / hover effects) and then build components. Chakra is just a design system whereas we are going to build components. We are just abstracting chakra to create atoms that can be used to build molecules and components.

**Comment by navin-moorthy** [comment]
> @navin-moorthy Ideal goal is to have wrappers on chakra for whatever it is missing (+) have a theme that is going to make it look good (with animations / hover effects) and then build components. Chakra is just a design system whereas we are going to build components. We are just abstracting chakra to create atoms that can be used to build molecules and components.

Okay, Okay, we are going to enhance Chakra component. and build the app with our components right?

**Comment by govindsingh55** [comment]
> > Also dot notation for primary secondary is missing
> 
> primary and secondary are probably the color variation right
> we can not define this color button is primary and this color button is secondary

@navin-moorthy @prasanna1211   any suggestions on this?

**Comment by prasanna1211** [comment]
@govindsingh55 they are not just the color variation. They might change their design too. For example in dashingdish. 
image

The font size changes and the color changes

At times the border might not be present for secondary. 

We need to identify what is going to change and group them to secondary.

**Comment by prasanna1211** [comment]
@navin-moorthy @govindsingh55 Can we have a call where I can explain more clear about my thoughts on what we are building (including this button) ?

**Pull request closed without merging**
