### PR TITLE
README.md, Package.json

### PR DESCRIPTION
**Pull request by SamrithaS**
Readme.md and package.json changes
#18

### CODE REVIEW

**Comment by prasanna1211** [comment]
@SamrithaS Few things, 
1. first the PR should be to be to development
2. Assign reviewer (must)
3. You can see if it is mergable (without conflicts). If conflicts are there you might need to do a rebase (we can help you out initially)

@govindsingh55 Can you review and approve the PR (or feedbacks). Look changed files if everything is correct and includes whatever is there in #19

**Comment by SamrithaS** [comment]
> @SamrithaS Few things,
> 
> 1. first the PR should be to be to development
> 2. Assign reviewer (must)
> 3. You can see if it is mergable (without conflicts). If conflicts are there you might need to do a rebase (we can help you out initially)
> 
> @govindsingh55 Can you review and approve the PR (or feedbacks). Look changed files if everything is correct and includes whatever is there in #19

A pr already exists from checkbox to development

**Comment by govindsingh55** [comment]
@SamrithaS always checkout new branch from development if working on a completely new feature and raise PR to development.
if the new feature is related to some branch then checkout from that branch and after finish raise PR to that particular parent branch.

**Comment by govindsingh55** [comment]
@prasanna1211 @navin-moorthy  do we need the react-boilerplate info in README.md

**Comment by prasanna1211** [comment]
No. Only the details to install and start the project.

**Pull request closed without merging**
